export const Colors = {
    background: '#ffffff',
    surface: '#f9f9f9',
    card: '#f9f9f9',
    text: '#0c0407',
    textSecondary: '#6b6b6b',
    textMuted: '#8f8f8f',
    accent: '#0c0407',
    border: '#dfdfdf',
    borderStrong: '#cccccc',
    line: '#cacaca',
    button: '#0c0407',
    buttonText: '#ffffff',
    invert: '#0c0407',
    invertText: '#ffffff',
    footerBackground: '#f9f9f9',
    gradientStart: '#ffffff',
    gradientEnd: '#f9f9f9',
};
